services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      # AI Service Configuration
      - AI_SERVICE=ollama
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=llama3.2:1b
      - TEMPERATURE=0.7
      # For production with Gemini, uncomment and set:
      # - AI_SERVICE=gemini
      # - GEMINI_API_KEY=your_api_key_here
      # - GEMINI_MODEL=gemini-pro
      # CORS Configuration
      - CORS_ORIGINS=http://localhost:5173
      # Email Service (optional - leave empty to disable)
      - SMTP_HOST=
      - SMTP_PORT=587
      - SMTP_USER=
      - SMTP_PASSWORD=
      - FROM_EMAIL=
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

  ollama:
    build: ./ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  ollama_data:

